#! /bin/fish

if not set -q argv[1]
	echo "must provide path of file to be created"
	exit 1
end

set tmp (mktemp)
trap 'rm $tmp' EXIT

read -s -P "password: " password
and vim $tmp
and gpg --yes --pinentry-mode loopback --passphrase $password -c --no-symkey-cache -o $argv[1].gpg $tmp < /dev/null
